### ISSUE TITLE
Wallace & Gromit game saves identified as other Telltale games

### ISSUE THREAD

**Issue by RiseT** [mtkennerly/ludusavi-manifest#24] opened 2023-03-14 16:29 UTC
Ludusavi identifies game saves of the Wallace & Gromit series (there are at least 4 games; I currently have only 2 of them installed) simultaneously as several other Telltale games.

For the sake of completeness, here are the titles of all Wallace & Gromit games I know of:

1. Fright of the Bumblebees
2. Muzzled!
3. The Bogey Man
4. The Last Resort

I cannot find these 4 games on PCGamingWiki; there are only 2 different Wallace & Gromit games listed:
https://www.pcgamingwiki.com/wiki/Series:Wallace_%26_Gromit

So I wonder where ludusavi gets the game save locations from.

![WallaceGromit1](https://user-images.githubusercontent.com/12624674/225060537-8d476a07-44e5-484b-a79f-28c28cd6fc8f.PNG)
![WallaceGromit2](https://user-images.githubusercontent.com/12624674/225060587-658e2f96-1e64-4591-9615-7299e7c306eb.PNG)
![WallaceGromit3](https://user-images.githubusercontent.com/12624674/225060638-dc44b171-ae7e-4027-b806-8ee53edc3c5b.PNG)

**Comment by mtkennerly** [comment] 2023-03-14 18:26
Hi! In this case, the issue is coming from the articles of the three games you see in the scan results. For example, the article for [Strong Bad's Cool Game for Attractive People](https://www.pcgamingwiki.com/wiki/Strong_Bad%27s_Cool_Game_for_Attractive_People) lists the save location as `%USERPROFILE%\Documents\Telltale Games\`, which is too generic.

**Comment by RiseT** [comment] 2023-03-14 19:22
Ah, I see, thanks. This case is complicated, though.

I happen to own Strong Bad's... as well and just installed it for the first time in order to take a look at its save game location. Strong Bad consists of 5 separate episodes (separate installs on Steam, though, which you all get with one single Steam key). And each episode creates its own save game folder in `%USERPROFILE%\Documents\Telltale Games\`.

The first episode's name is"Homestar Ruiner", thus it stores its saves in `%USERPROFILE%\Documents\Telltale Games\Homestar Ruiner`

I have no idea how to get this into PCGamingWiki's template (I'm new to PCGW, but this seems like a difficult one) - apart from treating each episode as a completely separate game.

**Comment by mtkennerly** [comment] 2023-03-14 19:50
You can use a pipe (`|`) between paths: `{{Game data/saves|Windows|path 1 here|path 2 here|etc...}}` . For example:

```
{{Game data/saves|Windows|{{p|userprofile\Documents}}\Telltale Games\Homestar Ruiner|{{p|userprofile\Documents}}\Telltale Games\Episode 2}}
```

...which would look like:

> <img width="623" alt="image" src="https://user-images.githubusercontent.com/4934192/225116777-30e45d59-0d7c-4215-8009-3cf9d4f557a2.png">

However, I [found a post](https://gaming.stackexchange.com/questions/117637/where-are-save-games-located-for-strong-bads-cool-game-for-attractive-people) that says the names are different for the Steam and non-Steam versions. There are a couple of ways to handle that:

* Use `{{Game data/saves|Steam|paths...` for the Steam paths and `{{Game data/saves|Windows|paths...` for the others
* Use a glob wildcard, like `{{Game data/saves|Windows|{{p|userprofile\Documents}}\Telltale Games\*Homestar Ruiner|{{p|userprofile\Documents}}\Telltale Games\*Strong Badia the Free}}`

Both options are valid. If you choose the second option, you might also add a note under the table, like:

```
{{ii}} {{code|*}} will be "Episode # -" for the non-Steam versions.
```

> <img width="284" alt="image" src="https://user-images.githubusercontent.com/4934192/225119132-93c86943-a608-45b9-910a-9c558f5a57b4.png">

**Comment by mtkennerly** [comment] 2023-03-14 21:43
Oh, it looks like you're right; I didn't realize that. I asked on the PCGamingWiki Discord server about it: https://discord.com/channels/165183350913499136/326048443040530432/1085314404372983889 , and they said they can add support for a fifth path tomorrow.

**Comment by RiseT** [comment] 2023-03-15 09:54
Done:
https://www.pcgamingwiki.com/wiki/Strong_Bad%27s_Cool_Game_for_Attractive_People

For the save files, I've used a wildcard for the file names in order to separate them from the config files, like this:
`{{p|userprofile\Documents}}\Telltale Games\Homestar Ruiner\*.save`

I hope this will work.

I wonder about [Back to the Future: The Game](https://www.pcgamingwiki.com/wiki/Back_to_the_Future:_The_Game), which has exactly the same problem.

Currently, the PCGW save game entry looks like this:
`{{Game data/saves|Windows|{{p|userprofile\Documents}}\Telltale Games\<episode name>\*.sav}}`

I don't think this will work with ludusavi, will it?

**Comment by RiseT** [comment] 2023-03-15 11:01
Tales of Monkey Island:

I've used
`{{Game data/config|Windows|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 1\prefs.prop|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 2\prefs.prop|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 3\prefs.prop|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 4\prefs.prop|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 5\prefs.prop}}`

and

`{{Game data/saves|Windows|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 1\*.save|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 2\*.save|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 3\*.save|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 4\*.save|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter 5\*.save}}`

and wonder if this is unnecessarily verbose.

Would
`{{Game data/config|Windows|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter ?\prefs.prop}}`

and
`{{Game data/saves|Windows|{{p|userprofile\Documents}}\Telltale Games\Tales of Monkey Island - Chapter ?\*.save}}`

do the job as well?

**Comment by mtkennerly** [comment] 2023-03-15 16:59
> `{{Game data/saves|Windows|{{p|userprofile\Documents}}\Telltale Games\<episode name>\*.sav}}`

Anything `<like this>` gets turned into `*` before going into the manifest.

I own Back to the Future, so I can try to check the Steam locations for it. Looks like the Windows/Mac names are on the wiki and just need to go into the table directly.

> Does the "?" in fact work as a wildcard for a single character on PCGW?

It does work (the `?` will go into the manifest, and Ludusavi will handle it as a glob), although I don't see `?` very often on the wiki. I'd probably recommend sticking with `*` unless you really need the specificity of `?`.

**Comment by RiseT** [comment] 2023-03-15 17:16
Thank you for the info.  One question regarding the wildcard `*`: Does this replace at least one character, i. e. is `test` (without additional characters) caught by `test*`?

**Comment by mtkennerly** [comment] 2023-03-15 17:35
`*` means "any number (even 0) of any characters other than a slash", so `test*` will match `test` as well. [Here's a demo](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2Ftmp%2Ffoo%2A%2Fa&matches=false&tests=%2Ftmp%2Ffoo%2Fa&tests=%2Ftmp%2Ffoo%2Fb&tests=%2Ftmp%2Fbar%2Fa&tests=%2Ftmp%2Ffoo%2Fbar%2Fa).

**Comment by RiseT** [comment] 2023-03-15 18:01
> Anything `<like this>` gets turned into `*` before going into the manifest.

So is `\Episode <number>\*.save` prefered to `\Episode *\*.save` on PCGW?

**Comment by RiseT** [comment] 2023-03-15 18:31
Case solved, duplicates removed 😃 (mh, well, there's no more Wallace & Gromit games; but they don't have their own pages on PCGM yet...)

![strongbad](https://user-images.githubusercontent.com/12624674/225407630-abf54756-0e59-40bb-b4d1-36d177464e80.PNG)
![bttf](https://user-images.githubusercontent.com/12624674/225407654-278aaf05-63c9-4bc1-bab2-bf51cbca729e.PNG)
![tomi](https://user-images.githubusercontent.com/12624674/225407673-d3d2d1b7-2341-4c23-a9c1-f0621a5bdd63.PNG)

**Comment by mtkennerly** [comment] 2023-03-15 18:49
Awesome!

> So is `\Episode <number>\*.save` prefered to `\Episode *\*.save` on PCGW?

Hmm, I think that's probably up to editor choice. I don't remember the style guide specifically addressing cases like that, at least the last time I checked.

**Comment by mtkennerly** [comment] 2023-03-16 18:21
The parsing issue is now fixed: https://github.com/mtkennerly/ludusavi-manifest/commit/16c3911354c1b8542c65517b18dfdda8ba707736 . However, this means that the save paths for [Sam & Max Save the World](https://www.pcgamingwiki.com/wiki/Sam_%26_Max_Save_the_World) (2007 original) are now properly parsed and included in the manifest as well, and they also need the proper episode names specified 😅 Do you happen to own it? It looks like it's only available as free DLC for the 2020 remaster. If not, I can get it and check.

**Comment by RiseT** [comment] 2023-03-16 19:50
That was fast. No, unfortunately I don't own that one.

**Comment by RiseT** [comment] 2023-03-16 20:09
Ugh, that one has 6 episodes ... (thinking of that limit that was just bumped from 4 to 5).

**Comment by mtkennerly** [comment] 2023-03-16 21:22
For now, I just added a filter to stop any `<winDocuments>/Telltale Games/*` paths from getting into the manifest, so Sam & Max Save the World is excluded again.

**Closed by mtkennerly** 2023-03-16 21:22 UTC

**Comment by RiseT** [comment] 2023-03-18 18:26
I own the Steam version of Sam & Max: The Devil’s Playhouse, though, and guess where it stores it's saves and config ...

**Comment by mtkennerly** [comment] 2023-03-18 18:58
Bah 😅 I added a few more exclusions: https://github.com/mtkennerly/ludusavi-manifest/commit/4d10900c3bd911d15d615041d50fc60a8851d01e

**Comment by RiseT** [comment] 2023-03-18 19:21
News regarding Save the World: [Link](https://steamcommunity.com/app/1440440/discussions/0/3818528846674172107/)

**Comment by RiseT** [comment] 2023-03-18 19:29
Regarding Save the World:
Mmh - is that really the info we need? Or is this just the location of the game's executables? Or both?
https://steamcommunity.com/app/1440440/discussions/0/3818528846674172107/)](https://steamcommunity.com/app/1440440/discussions/0/3818528846674172107/

**Comment by mtkennerly** [comment] 2023-03-18 19:50
Sounds like both, or at least that's how I interpreted it. Could add an entry like this:

```
{{Game data/saves|Steam|{{p|game}}\ep*\*.save}}
```

**Comment by RiseT** [comment] 2023-03-19 15:15
Example [The Devil's Playhouse](https://www.pcgamingwiki.com/wiki/Sam_%26_Max:_The_Devil%27s_Playhouse):

If the info I have about the config and save location is from the Steam version, but PCGW's current `Windows` entry is empty: Should I put my info rather under `Windows` or `Steam`? (kind of both is true; it's the Steam version running on Windows)

**Comment by mtkennerly** [comment] 2023-03-19 19:19
I think you'd use `Windows` unless the Steam and standalone Windows versions use different paths. When you're not sure if they're different, then I'm not sure, but I would assume it probably defaults to `Windows`.

https://www.pcgamingwiki.com/wiki/PCGamingWiki:Editing_guide/Game_data

> Games with multiple distribution versions on the same OS (ex. Steam, Origin) should have separate rows if files are placed differently.

> For example separate Steam and Origin rows would list where those platforms store files, while a general Windows row would list DRM-free releases or platforms without unique locations specific to a single platform.
